# Generated by Django 4.2 on 2024-10-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="content_type",
        ),
        migrations.AddField(
            model_name="question",
            name="content_type",
            field=models.CharField(
                choices=[("1", "TEXT"), ("2", "RANGE"), ("3", "RADIO"), ("4", "CHECK")],
                default=1,
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
