# Generated by Django 4.2 on 2024-10-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_alter_aihistory_answer_alter_aihistory_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetWikiImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="pets/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "PID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pet_images",
                        to="pets.petcode",
                    ),
                ),
            ],
        ),
    ]
