# Generated by Django 4.2 on 2024-10-04 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pets", "0003_petwikiimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aihistory",
            name="UID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="aihistorys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
