# Generated by Django 4.2 on 2024-10-04 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeBoard",
            fields=[
                (
                    "board_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="boards.board",
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
            bases=("boards.board",),
        ),
    ]
